model:
  _target_: src.model.Generator
  upsample_kernel_sizes: [16,16,4,4]
  upsample_initial_channel: 512
  prepost_conv_kernel_size: 7
  mrf_kernel_sizes: [3,7,11]
  mrf_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
  n_mels: 80
  get_spectrogram: # special key for getting spectrogram
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 22050
    n_fft: 1024
    win_length: 1024
    hop_length: 256
    n_mels: 80
    f_max: 8000
    center: False
    pad: 384
